"""took care of karma null error

Revision ID: 138ea095decd
Revises: 574cedb451b3
Create Date: 2015-11-02 21:13:09.351596

"""

# revision identifiers, used by Alembic.
revision = '138ea095decd'
down_revision = '574cedb451b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
