"""empty message

Revision ID: 3357abca3bfe
Revises: 8640e27bf80
Create Date: 2015-11-02 21:01:10.570322

"""

# revision identifiers, used by Alembic.
revision = '3357abca3bfe'
down_revision = '8640e27bf80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
