"""added Downvoted and Upvoted

Revision ID: 3de8be8e1671
Revises: b55903d2a88
Create Date: 2015-11-03 09:28:46.112705

"""

# revision identifiers, used by Alembic.
revision = '3de8be8e1671'
down_revision = 'b55903d2a88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
