"""empty message

Revision ID: 574cedb451b3
Revises: 3357abca3bfe
Create Date: 2015-11-02 21:07:47.351049

"""

# revision identifiers, used by Alembic.
revision = '574cedb451b3'
down_revision = '3357abca3bfe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
