"""initial migration

Revision ID: 8640e27bf80
Revises: 51f5ccfba190
Create Date: 2015-11-02 20:53:38.481198

"""

# revision identifiers, used by Alembic.
revision = '8640e27bf80'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('karma', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'karma')
    ### end Alembic commands ###
