"""added Downvoted and Upvoted

Revision ID: b55903d2a88
Revises: 138ea095decd
Create Date: 2015-11-03 09:26:10.609360

"""

# revision identifiers, used by Alembic.
revision = 'b55903d2a88'
down_revision = '138ea095decd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downvoted',
    sa.Column('downvoter_id', sa.Integer(), nullable=False),
    sa.Column('downvoted_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['downvoted_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['downvoter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('downvoter_id', 'downvoted_id')
    )
    op.create_table('upvoted',
    sa.Column('upvoter_id', sa.Integer(), nullable=False),
    sa.Column('upvoted_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['upvoted_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['upvoter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('upvoter_id', 'upvoted_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upvoted')
    op.drop_table('downvoted')
    ### end Alembic commands ###
